export type ProjectCategory = "Product Design" | "Engineering" | "User Research" | "Industrial Design"

export interface Project {
  title: string
  href: string
  image: string
  year: string
  action: string
  description: string
  tags: string[]
  category: ProjectCategory
}

export const projects: Project[] = [
  {
    title: "Solving ARC-AGI",
    href: "/kbai",
    image: "/projects/KBAI-thumbnail.png",
    year: "2025",
    action: "Artificial Intelligence",
    description: "Built a Knowledge-Based Agent that Solves Visual Reasoning Puzzles",
    tags: ["Georgia Tech", "Python", "Artificial Intelligence"],
    category: "Engineering",
  },
  {
    title: "ML-Driven Algorithmic Trading",
    href: "/ml4t",
    image: "/projects/ML4T.png",
    year: "2024",
    action: "Machine Learning",
    description: "Built an ML Trading Pipeline from Scratch",
    tags: ["Georgia Tech", "Python", "Machine Learning"],
    category: "Engineering",
  },
  {
    title: "Android Demo App",
    href: "/android-demo-app",
    image: "/projects/ML4T.png",
    year: "2025",
    action: "View Case Study",
    description: "Job comparison Android app with SQLite, layered architecture, and weighted scoring engine",
    tags: ["Georgia Tech", "Java", "Android"],
    category: "Engineering",
  },
  {
    title: "PayPal Social Payment",
    href: "/paypal-social-payment",
    image: "/projects/paypal-social-payment_L.png",
    year: "2019-2024",
    action: "Product Design",
    description: "Lead Product Designer for PayPal's Social Payments",
    tags: ["PayPal", "Consumer", "P2P"],
    category: "Product Design",
  },
  {
    title: "SAP Copilot",
    href: "/sap-copilot",
    image: "/projects/sap-copilot.png",
    year: "2016-2019",
    action: "Product Design",
    description: "Designed an AI Copilot for Enterprise Workflows",
    tags: ["SAP", "Enterprise", "Design System"],
    category: "Product Design",
  },
  {
    title: "SAP Fiori for iOS",
    href: "/sap-fiori-ios",
    image: "/projects/sap-fiori-ios.png",
    year: "2016-2019",
    action: "Product Design",
    description: "Built iOS Design Language for SAP Fiori",
    tags: ["SAP", "iOS", "Design System"],
    category: "Product Design",
  },
  {
    title: "Pinterest Explorer",
    href: "/pinterest-explorer",
    image: "/projects/pinterest-explorer.jpg",
    year: "2016",
    action: "Product Design",
    description: "UX Strategy for Pinterest Discovery",
    tags: ["UX Design", "Strategy"],
    category: "Product Design",
  },
  {
    title: "Ryanair Adventure",
    href: "/ryanair-adventure",
    image: "/projects/ryanair-adventure.png",
    year: "2014-2016",
    action: "View Case Study",
    description: "Redesigned the Adventure Travel Experience",
    tags: ["Ryanair", "Travel", "UX"],
    category: "Product Design",
  },
  {
    title: "Discharge Doc Evaluation",
    href: "/discharge-doc-evaluation",
    image: "/projects/discharge-doc-eval.jpg",
    year: "2014-2016",
    action: "User Research",
    description: "Evaluated Hospital Discharge Documentation",
    tags: ["Healthcare", "User Research", "Communication"],
    category: "User Research",
  },
  {
    title: "COPD Management",
    href: "/copd-management",
    image: "/projects/copd-management.jpg",
    year: "2014-2016",
    action: "User Research",
    description: "Designed COPD Patient Communication",
    tags: ["Healthcare", "User Research", "Communication"],
    category: "User Research",
  },
  {
    title: "Portfolio Planning for Crane",
    href: "/crane",
    image: "/projects/portfolio-planning-crane.jpg",
    year: "2014-2016",
    action: "View Case Study",
    description: "Portfolio Planning Tool for Crane Co.",
    tags: ["Enterprise", "Strategy", "UX"],
    category: "User Research",
  },
  {
    title: "Guardian",
    href: "/guardian",
    image: "/projects/guardian.jpg",
    year: "2013",
    action: "Industrial Design",
    description: "Guardian Personal Safety Device",
    tags: ["Healthcare", "Industrial Design"],
    category: "Industrial Design",
  },
  {
    title: "Matrix C",
    href: "/c-matrix",
    image: "/projects/matrix-c.jpg",
    year: "2013",
    action: "Industrial Design",
    description: "Matrix C — Customize Your Lighting",
    tags: ["Industrial Design", "Creative Tech"],
    category: "Industrial Design",
  },
  {
    title: "Fixpert",
    href: "/fixpert",
    image: "/projects/fixpert.jpg",
    year: "2012",
    action: "Service Design",
    description: "Fixpert DIY Repair Community Platform",
    tags: ["Service Design", "Community"],
    category: "Product Design",
  },
  {
    title: "Cycle Bike",
    href: "/tongjibike",
    image: "/projects/tongjibike/exhibition.jpg",
    year: "2012",
    action: "Service Design",
    description: "Sustainable Bike Loaning & Recycling System",
    tags: ["Service Design", "Sustainability"],
    category: "Industrial Design",
  },
  {
    title: "Pure",
    href: "/pure",
    image: "/projects/pure.png",
    year: "2012",
    action: "Industrial Design",
    description: "A Crafted Magnetic Pen",
    tags: ["Industrial Design", "Craft"],
    category: "Industrial Design",
  },
  {
    title: "Sub",
    href: "/sub",
    image: "/projects/sub.jpg",
    year: "2012",
    action: "Industrial Design",
    description: "An Under-Desk Printer That Saves Your Back",
    tags: ["Industrial Design", "Prototype"],
    category: "Industrial Design",
  },
]
