export interface Project {
  title: string
  href: string
  image: string
  year: string
  action: string
  description: string
  tags: string[]
}

export const projects: Project[] = [
  {
    title: "PayPal Social Payment",
    href: "/paypal-social-payment",
    image: "/projects/paypal-social-payment_L.png",
    year: "2019-2024",
    action: "Product Design",
    description: "Lead Product Designer for PayPal's Social Payments",
    tags: ["PayPal", "Consumer", "P2P"],
  },
  {
    title: "SAP Copilot",
    href: "/sap-copilot",
    image: "/projects/sap-copilot.png",
    year: "2018",
    action: "View Case Study",
    description: "Designed an AI Copilot for Enterprise Workflows",
    tags: ["SAP", "Enterprise", "AI"],
  },
  {
    title: "SAP Fiori for iOS",
    href: "https://www.jieyangdesign.com/pinterest-explorer-ux-strategy-2/",
    image: "/projects/sap-fiori-ios.png",
    year: "2018",
    action: "View Gallery",
    description: "Built iOS Design Language for SAP Fiori",
    tags: ["SAP", "iOS", "Design System"],
  },
  {
    title: "Pinterest Explorer",
    href: "https://www.jieyangdesign.com/pinterest-explorer-ux-strategy/",
    image: "/projects/pinterest-explorer.jpg",
    year: "2016",
    action: "View Case Study",
    description: "UX Strategy for Pinterest Discovery",
    tags: ["Pinterest", "UX Strategy", "Discovery"],
  },
  {
    title: "Ryanair Adventure",
    href: "https://www.jieyangdesign.com/ryanair-pass/",
    image: "/projects/ryanair-adventure.png",
    year: "2016",
    action: "View Case Study",
    description: "Redesigned the Adventure Travel Experience",
    tags: ["Ryanair", "Travel", "UX"],
  },
  {
    title: "Discharge Doc Evaluation",
    href: "https://www.jieyangdesign.com/discharge-document-evaluation/",
    image: "/projects/discharge-doc-eval.jpg",
    year: "2016",
    action: "View Case Study",
    description: "Evaluated Hospital Discharge Documentation",
    tags: ["Healthcare", "Research", "UX"],
  },
  {
    title: "COPD Management",
    href: "https://www.jieyangdesign.com/communication-design/",
    image: "/projects/copd-management.jpg",
    year: "2016",
    action: "View Case Study",
    description: "Designed COPD Patient Communication",
    tags: ["Healthcare", "Communication", "UX"],
  },
  {
    title: "Portfolio Planning for Crane",
    href: "https://www.jieyangdesign.com/new-page-1/",
    image: "/projects/portfolio-planning-crane.jpg",
    year: "2016",
    action: "View Case Study",
    description: "Portfolio Planning Tool for Crane Co.",
    tags: ["Enterprise", "Strategy", "UX"],
  },
  {
    title: "Guardian",
    href: "https://www.jieyangdesign.com/guardian/",
    image: "/projects/guardian.jpg",
    year: "2015",
    action: "View Project",
    description: "Guardian Personal Safety Device",
    tags: ["Safety", "IoT", "Industrial"],
  },
  {
    title: "Matrix C",
    href: "https://www.jieyangdesign.com/c-matrix/",
    image: "/projects/matrix-c.jpg",
    year: "2016",
    action: "View Gallery",
    description: "Matrix C Industrial Design Gallery",
    tags: ["Industrial", "Gallery"],
  },
  {
    title: "Fixpert",
    href: "https://www.jieyangdesign.com/fixpert/",
    image: "/projects/fixpert.jpg",
    year: "2016",
    action: "View Gallery",
    description: "Fixpert DIY Repair Community Platform",
    tags: ["Mobile", "Community", "UX"],
  },
  {
    title: "Cycle Bike",
    href: "https://www.jieyangdesign.com/tongjibike/",
    image: "/projects/cycle-bike.jpg",
    year: "2016",
    action: "View Gallery",
    description: "Sustainable Urban Bike Design",
    tags: ["Industrial", "Transport"],
  },
  {
    title: "Pure",
    href: "https://www.jieyangdesign.com/pure/",
    image: "/projects/pure.png",
    year: "2016",
    action: "View Gallery",
    description: "Pure Minimal Product Design",
    tags: ["Industrial", "Minimal"],
  },
  {
    title: "Sub",
    href: "https://www.jieyangdesign.com/sub/",
    image: "/projects/sub.jpg",
    year: "2016",
    action: "View Project",
    description: "Sub Submarine-Inspired Concept Design",
    tags: ["Industrial", "Concept"],
  },
]
